services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    # networks:
    #   - mynetworks

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ballerbraindb
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - my_pgdata:/var/lib/postgresql/data

volumes:
  my_pgdata:
